export const PELABUHAN_OPTIONS = [
  "Pelabuhan Perikanan Banyusangka",
  "Pelabuhan Perikanan Bawean",
  "Pelabuhan Perikanan Branta Pesisir",
  "Pelabuhan Perikanan Bulu",
  "Pelabuhan Perikanan Camplong",
  "Pelabuhan Perikanan Campurejo",
  "Pelabuhan Perikanan Grajagan",
  "Pelabuhan Perikanan Lekok",
  "Pelabuhan Perikanan Mayangan",
  "Pelabuhan Perikanan Muncar",
  "Pelabuhan Perikanan Ngemplakrejo",
  "Pelabuhan Perikanan Paiton",
  "Pelabuhan Perikanan Pancer",
  "Pelabuhan Perikanan Pasongsongan",
  "Pelabuhan Perikanan Pondokdadap",
  "Pelabuhan Perikanan Popoh",
  "Pelabuhan Perikanan Puger",
  "Pelabuhan Perikanan Sine",
  "Pelabuhan Perikanan Tambakrejo",
  "Pelabuhan Perikanan Tamperan"
];

export const KAB_KOTA_GT_KAPAL_OPTIONS = [
  'Perahu Tanpa Motor',
  'Motor Tempel < 5 GT',
  'Motor Tempel 5-10 GT',
  'Motor Tempel 10-20 GT',
  'Motor Tempel 20-30 GT',
  'Motor Tempel > 30 GT',
  'Kapal Motor < 5 GT',
  'Kapal Motor 5-10 GT',
  'Kapal Motor 10-20 GT',
  'Kapal Motor 20-30 GT',
  'Kapal Motor 30-50 GT',
  'Kapal Motor 50-100 GT',
  'Kapal Motor 100-200 GT',
  'Kapal Motor 200-300 GT',
  'Kapal Motor 300-500 GT',
  'Kapal Motor 500-1000 GT',
  'Kapal Motor > 1000 GT'
];

export const GT_KAPAL_OPTIONS = [
  "GT 101 - 200",
  "GT 11 - 20",
  "GT 201 - 300",
  "GT 21 - 30",
  "GT 301 - 500",
  "GT 31 - 50",
  "GT 501 - 1000",
  "GT 51 - 100",
  "GT 6 - 10",
  "GT < 5",
  "GT > 1000",
  "GT > 30",
  "Jukung",
  "Perahu Papan Besar",
  "Perahu Papan Kecil",
  "Perahu Papan Sedang"
];

export const ALAT_TANGKAP_OPTIONS = [
  "Ambai",
  "Anco",
  "Bagan Berperahu Teri atau Bagan Apung Teri",
  "Bagan Berperahu atau Bagan Apung",
  "Bagan Tancap",
  "Bale-bale",
  "Bouke Ami",
  "Bubu",
  "Bubu Bersayap",
  "Bubu Bersayap Glass Eel",
  "Bubu Gurita",
  "Bubu Naga",
  "Huhate",
  "Huhate Mekanis",
  "Jala Jatuh Berkapal",
  "Jala Tebar",
  "Jaring Hela Dasar",
  "Jaring Hela Ikan Berkantong",
  "Jaring Hela Udang Berkantong",
  "Jaring Insang Berlapis",
  "Jaring Insang Berpancang",
  "Jaring Insang Hanyut",
  "Jaring Insang Horizontal",
  "Jaring Insang Kombinasi",
  "Jaring Insang Lingkar",
  "Jaring Insang Tetap",
  "Jaring Lingkar Tanpa Tali Kerut",
  "Jaring Tarik Berkantong",
  "Jaring Tarik Pantai",
  "Jaring Tarik Sempadan",
  "Jermal",
  "Ladung",
  "Panah",
  "Pancing Berjoran",
  "Pancing Cumi",
  "Pancing Cumi Mekanis",
  "Pancing Layang-Layang",
  "Pancing Ulur",
  "Pancing Ulur Tuna",
  "Payang",
  "Payang Teri",
  "Pengerih",
  "Penggaruk Berkapal",
  "Penggaruk Tanpa Kapal",
  "Perangkap Benih Bening Lobster dan Benih Lobster",
  "Perre-Perre",
  "Pukat Cincin Pelagis Besar dalam Kesatuan Armada",
  "Pukat Cincin Pelagis Besar dengan Satu Kapal",
  "Pukat Cincin Pelagis Kecil dalam Kesatuan Armada",
  "Pukat Cincin Pelagis Kecil dengan Dua Kapal",
  "Pukat Cincin Pelagis Kecil dengan Satu Kapal",
  "Pukat Cincin Teri dengan Satu Kapal",
  "Pukat Dorong",
  "Pukat Labuh",
  "Pukat Labuh Teri",
  "Rawai Dasar",
  "Rawai Tuna",
  "Sero",
  "Seser",
  "Set net",
  "Togo",
  "Tombak",
  "Tonda"
];

export const KOMODITAS_OPTIONS = [
  "Albakora (Thunnus alalunga)",
  "Alu- alu (Sphyraena qenie)",
  "Alu-alu (Sphyraena barracuda)",
  "Alu-alu (Sphyraena obtusata)",
  "Anggoli (Etelis coruscans)",
  "Aruan tasek (Rachycentron canadum )",
  "Baji-baji sebra (Seriolina nigrofasciata )",
  "Bambangan (Lutjanus malabaricus)",
  "Barakuda (Sphyraena jello)",
  "Baronang (Siganus javus)",
  "Baronang lingkis  (Siganus canaliculatus)",
  "Bawal (Colossoma macropomum)",
  "Bawal hitam (Parastromateus niger)",
  "Bawal putih  (Pampus argenteus)",
  "Bawal sabit (Taractichthys steindachneri)",
  "Belanak (Mugil cephalus)",
  "Beloso (Saurida tumbil)",
  "Biji nangka (Upeneus moluccensis)",
  "Biji nangka (Upeneus spp)",
  "Bulan - Bulan (Megalops cyprinoides)",
  "Buntal karang (Diodon hystrix)",
  "Butana (Acanthurus mata)",
  "Cakalang (Katsuwonus pelamis)",
  "Cendro (Belonidae)",
  "Cendro (Tylosurus crocodilus)",
  "Cipa-cipa (Argyrops spinifer)",
  "Cobia (Rachycentron canadum )",
  "Coklatan (Scolopsis affinis)",
  "Cucut baster (Isurus paucus)",
  "Cucut lanjam (Carcharhinus cautus)",
  "Cucut lanjam (Carcharhinus melanopterus)",
  "Cucut mako (Isurus spp)",
  "Cucut martil (Eusphyra blochii)",
  "Cumi karet (Sthenoteuthis oualaniensis)",
  "Cumi-cumi (Loligo chinensis)",
  "Cumi-cumi (Loligo duvauceli)",
  "Cumi-cumi (Loligo edulis)",
  "Cumi-cumi (Loligo spp)",
  "Cumi-cumi (Loligo vulgaris)",
  "Gemprang (Ilisha elongata)",
  "Gerot-gerot (Pomadasys argenteus)",
  "Gerot-gerot (Pomadasys argyreus)",
  "Gindara (Ruvettus pretiosus)",
  "Golok-golok (Chirocentrus dorab)",
  "Gorara (Lutjanus russelli)",
  "Gorara gigi (Lutjanus erythropterus)",
  "Gulamah (Gymnocranius griseus)",
  "Gulamah (Johnius coitor)",
  "Gulamah (Otolithes ruber)",
  "Gulamah (Panna microdon)",
  "Gulamah (Pennahia argentata)",
  "Gulamah keken (Johnius amblycephalus)",
  "Gulamah papan (Chrysochir aureus)",
  "Gulamah putih (Johnius borneensis)",
  "Gurita (Octopus spp)",
  "Hiu air (Scoliodon laticaudus)",
  "Hiu bongol (Chiloscyllium punctatum)",
  "Hiu lanjam (Carcharhinus amblyrhynchoides )",
  "Hiu lonjor (Carcharhinus spp)",
  "Hiu putik (Mustelus manazo)",
  "Hiu tokek (Atelomycterus marmoratus)",
  "Ikan ayam-ayam (Abalistes stellaris)",
  "Ikan jaket (Aluterus monoceros)",
  "Ikan kakatua (Scarus spp)",
  "Ikan lainnya",
  "Ikan layaran (Istiophorus platypterus)",
  "Ikan lemah (Lactarius lactarius)",
  "Ikan merah (Lutjanus erythropterus)",
  "Ikan pedang (Xiphias gladius)",
  "Ikan sebelah (Psettodes erumei)",
  "Ikan sebelah mata kanan (Poecilopsetta colorata)",
  "Ikan Setan (Lepidocybium flavobrunneum)",
  "Jambian (Lutjanus lutjanus)",
  "Japuh (Dussumieria acuta)",
  "Kaci-kaci (Diagramma labiosum)",
  "Kaci-kaci (Plectorhinchus flavomaculatus",
  "Kaci-kaci (Plectorhinchus spp)",
  "Kakap (Choerodon anchorago)",
  "Kakap jenaha (Lutjanus johnii)",
  "Kakap Merah (Lutjanus bitaeniatus)",
  "Kakap merah (Lutjanus spp)",
  "Kakap merah (Lutjanus timorensis)",
  "Kapas-Kapas (Gerres filamentosus)",
  "Kapas-kapas (Lutjanus monostigma)",
  "Kea-kea (Siganus virgatus)",
  "Kembung lelaki (Rastrelliger kanagurta)",
  "Kembung perempuan (Rastrelliger brachysoma)",
  "Kenyar (Sarda orientalis)",
  "Kerapu (Cephalopholis aurantia)",
  "Kerapu (Epinephelus cyanopodus)",
  "Kerapu (Epinephelus radiatus)",
  "Kerapu bintik kuning (Epinephelus timorensis)",
  "Kerapu karang (Cephalopholis boenak)",
  "Kerapu lumpur (Epinephelus amblycephalus)",
  "Kerapu lumpur (Epinephelus bleekeri)",
  "Kerapu sunu (Plectropomus leopardus)",
  "Kerapu tutul (Epinephelus coioides)",
  "Kerisi (Etelis radiosus)",
  "Kerisi (Nemipterus spp)",
  "Kerisi (Pentapodus emeryii)",
  "Kerong-kerong (Lethrinus spp)",
  "Kerong-kerong (Terapon theraps)",
  "Kerong-kerong padi (Terapon puta)",
  "Ketambak (Lethrinus laticaudis)",
  "Ketang-ketang (Drepane punctata)",
  "Kuniran (Upeneus sulphureus)",
  "Kurisi (Nemipterus aurora)",
  "Kurisi (Nemipterus nematophorus)",
  "Kurisi (Nemipterus virgatus )",
  "Kurisi (Nemipterus virgatus)",
  "Kurisi bali (Pristipomoides filamentosus)",
  "Kurisi perak (Aphareus Rutilans)",
  "Kuro (Eleutheronema tetradactylum)",
  "Kuro (Polydactylus microstomus)",
  "Kuwe (Carangoides hedlandensis)",
  "Kuwe (Carangoides malabaricus)",
  "Kuwe (Carangoides oblongus)",
  "Kuwe (Caranx sexfasciatus)",
  "Kuwe (Caranx spp)",
  "Kuwe abu-abu sirip gelap (Carangoides caeruleopinnatus )",
  "Kuwe abu-abu sirip gelap (Seriola rivoliana)",
  "Kuwe moncong tumpul bulat (Carangoides ferdau)",
  "Layang (Decapterus maruadsi)",
  "Layang anggur (Decapterus kurroides)",
  "Layang benggol (Decapterus russelli)",
  "Layang deles (Decapterus macrosoma)",
  "Layang pectoralf pendek (Decapterus macarellus)",
  "Layang spp (Decapterus spp)",
  "Layur (Lepturacanthus savala)",
  "Layur (Trichiurus lepturus)",
  "Lemadang (Coryphaena hippurus)",
  "Lemuru (Sardinella lemuru)",
  "Lencam (Lethrinus lentjan)",
  "Lencam (Lethrinus spp)",
  "Lolosi biru (Caesio caerulaurea)",
  "Madidihang (Thunnus albacares)",
  "Mala (Gymnocranius elongatus)",
  "Mala (Lutjanus vitta)",
  "Manyung (Arius spp)",
  "Manyung (Netuma thalassina)",
  "Marlin biru (Makaira nigricans)",
  "Mujair (Oreochromis mossambicus )",
  "Nyunglas (Acanthocybium solandri )",
  "Parang (Macrochirichthys macrochirus )",
  "Pari burung (Aetomylaeus niehofii)",
  "Pari kekeh (Rhinobatos spp)",
  "Pari kekeh (Rhynchobatus australiae)",
  "Pari kelapa (Pastinachus ater)",
  "Pari kembang (Dasyatis kuhlii)",
  "Pari merica (Taeniura lymma)",
  "Pari mutiara (Himantura jenkinsii)",
  "Pasir-pasir (Scolopsis bilineata)",
  "Pasir-pasir (Scolopsis taenioptera)",
  "Peperek (Leiognathus berbis)",
  "Peperek (Leiognathus leuciscus)",
  "Peperek bondolan (Gazza minuta)",
  "Peperek bondolan (Leiognathus bindus)",
  "Peperek lainnya (Leiognathus spp)",
  "Peperek topang (Leiognathus equulus)",
  "Pilok (Mene maculata)",
  "Pinjala (Pristipomoides multidens )",
  "Pinjalo (Pristipomoides typus)",
  "Pisang-pisang (Caesio cuning)",
  "Rajungan (Portunus pelagicus)",
  "Rajungan (Portunus spp)",
  "Rajungan angin (Podophthalmus vigil)",
  "Rejum (Sillago sihama)",
  "Remang (Gymnothorax spp)",
  "Remang putih (Gymnothorax undulatus)",
  "Selanget (Anodontostoma chacunda)",
  "Selar (Alepes melanoptera)",
  "Selar (Selar boops)",
  "Selar bentong (Selar crumenophthalmus)",
  "Selar hijau (Atule mate)",
  "Selar komo (Alepes djedaba)",
  "Selar kuning (Selaroides leptolepis)",
  "Semar (Lampris guttatus)",
  "Sembilang (Plotosus canius)",
  "Setuhuk hitam (Istiompax indica ; Makaira Indica)",
  "Silper (Platax boersii)",
  "Siro (Amblygaster sirm)",
  "Sokang (Trachinotus blochii)",
  "Sotong (Sepia aculeata)",
  "Sotong (Sepia officinalis)",
  "Sotong (Sepia pharaonis)",
  "Sotong (Sepia recurvirostra)",
  "Sotong (Sepia spp)",
  "Sunglir (Elagatis bipinnulata)",
  "Swanggi (Priacanthus hamrur)",
  "Swanggi (Priacanthus tayenus)",
  "Talang- talang (Scomberoides tol)",
  "Talang-talang (Scomberoides commersonnianus )",
  "Talang-talang (Scomberoides tala)",
  "Tanda-tanda batu (Lutjanus decussatus)",
  "Tembang (Sardinella albella)",
  "Tembang (Sardinella fimbriata)",
  "Tembang (Sardinella gibbosa)",
  "Tembang Sardinella brachysoma)",
  "Tenggiri (Scomberomorus commerson )",
  "Tenggiri papan (Scomberomorus guttatus)",
  "Teri (Encrasicholina devisi)",
  "Teri (Encrasicholina spp)",
  "Teri (Stolephorus commersonii)",
  "Terman (Ulua mentalis)",
  "Tetengkek (Megalaspis cordyla)",
  "Tigawaja (Johnius dussumieri)",
  "Tongkol abu-abu (Thunnus tonggol)",
  "Tongkol banyar (Euthynnus affinis)",
  "Tongkol banyar (Euthynnus lineatus)",
  "Tongkol pisang-balaki (Auxis thazard)",
  "Tongkol pisang-cerutu (Auxis rochei)",
  "Tuna mata besar (Thunnus obesus)",
  "Udang jerbung (Penaeus merguiensis )",
  "Udang kipas (Thenus orientalis)",
  "Udang krosok (Metapenaeus spp)",
  "Udang krosok merah (Metapenaeopsis rosea)",
  "Udang pasir (Thenus orientalis)",
  "Udang putih vanamei (Penaeus vannamei)"
];

// ----------------------------------------------------
// MASTER DATA KHUSUS PUD (Perairan Umum Daratan) & KAB/KOTA
// ----------------------------------------------------

export const KAB_KOTA_OPTIONS = [
  "Bangkalan", "Banyuwangi", "Blitar", "Bojonegoro", "Bondowoso", "Gresik", "Jember", 
  "Jombang", "Kediri", "Kota Batu", "Kota Blitar", "Kota Kediri", "Kota Madiun", 
  "Kota Malang", "Kota Mojokerto", "Kota Pasuruan", "Kota Probolinggo", "Kota Surabaya", 
  "Lamongan", "Lumajang", "Madiun", "Magetan", "Malang", "Mojokerto", "Nganjuk", "Ngawi", 
  "Pacitan", "Pamekasan", "Pasuruan", "Ponorogo", "Probolinggo", "Sampang", "Sidoarjo", 
  "Situbondo", "Sumenep", "Trenggalek", "Tuban", "Tulungagung"
];

export const PERAIRAN_OPTIONS = [
  "Sungai",
  "Danau",
  "Waduk",
  "Rawa",
  "Genangan"
];

export const KOMODITAS_PUD_OPTIONS = [
  "Betok", "Sidat", "Belut", "Baung", "Tapah", "Keting", "Sepat rawa", "Sepat siam", "Gabus", 
  "Toman", "Mujair", "Nila", "Lele", "Botia", "Berukung", "Beunteur", "Bilih", "Depik", 
  "Genggehek", "Uceng", "Hampal", "Jelawat", "Kancera", "Kendia", "Koan", "Lalang", "Lalawak", 
  "Lukas", "Mas", "Nilem", "Parang", "Parai/Seluang", "Repang", "Salab/Lampan", "Semah", "Seren", 
  "Tawes", "Tontong tebu", "Betutu", "Tambakan", "Sili", "Belida", "Gurame", "Siluk", "Patin jambal", "Udang grago", "Udang galah", "Buaya", "Katak benggala",];

export const ALAT_TANGKAP_PUD_OPTIONS = [
  "Hanyut", "Tetap", "Jala", "Serok", "Anco", "Bagan Perahu", "Rawai", "Pancing", "Sero", "Bubu", "Perangkap lain"
];

export const PUD_JENIS_PERAHU_OPTIONS = [
  'Tanpa Perahu',
  'Perahu Tanpa Motor',
  'Motor Tempel < 5 GT',
  'Kapal Motor 5-10 GT',
  'Kapal Motor 10-20 GT',
  'Kapal Motor 20-30 GT',
  'Kapal Motor >30 GT'
];

export const ALAT_TANGKAP_LAUT_OPTIONS = [
  "Pukat cincin pelagis kecil dengan satu kapal", "Pukat cincin pelagis besar dengan satu kapal", "Pukat cincin teri dengan satu kapal", "Pukat cincin pelagis kecil dengan dua kapal",
  "Jaring lingkar tanpa tali kerut", "Jaring tarik pantai", "Payang", "Dogol", "Jaring tarik berkantong",
  "Jaring hela udang berkantong", "Jaring hela ikan berkantong",
  "Penggaruk berkapal", "Penggaruk tanpa kapal",
  "Anco", "Bagan berperahu atau bagan apung", "Bouke ami", "Bagan tancap",
  "Jala jatuh berkapal", "Jala tebar",
  "Jaring insang tetap", "Jaring insang hanyut", "Jaring insang lingkar", "Jaring insang berpancang", "Jaring insang berlapis", "Jaring insang kombinasi",
  "Set net", "Bubu", "Bubu bersayap", "Pukat labuh", "Togo", "Ambai", "Jermal", "Pengerih", "Sero", "Perangkap Lainnya",
  "Pancing ulur", "Pancing ulur tuna", "Pancing berjoran", "Pancing cumi", "Pancing cumi mekanis", "pancing layang-layang", "Huhate", "Huhate mekanis", "Rawai dasar", "Rawai tuna", "Tonda",
  "Tombak", "Ladung", "Panah", "Pukat dorong", "Seser", "Pocongan",
  "Alat Tangkap Lainnya"
];

export const KOMODITAS_LAUT_OPTIONS = [
  "Teri",
  "Teri nasi",
  "Belanak",
  "Bentong",
  "Cendro",
  "Daun bambu/Talang-talang",
  "Ikan terbang",
  "Japuh",
  "Julung-julung",
  "Banyar",
  "Kembung",
  "Layang anggur/Malalugis",
  "Layang deles",
  "Layang biru",
  "Layang benggol",
  "Lemuru",
  "Siro",
  "Selar komo",
  "Selar hijau",
  "Selar kuning",
  "Sunglir",
  "Tembang",
  "Selanget",
  "Terubuk",
  "Tetengkek",
  "Semar",
  "Bandeng",
  "Nike",
  "Albakora (ALB)",
  "Tuna mata besar (BET)",
  "Tuna sirip biru selatan (SBT)",
  "Tuna gigi anjing",
  "Madidihang (YFT)",
  "Tongkol abu-abu (LOT)",
  "Tongkol komo (KAW)",
  "Tongkol krai (FRI)",
  "Lisong (BLT)",
  "Kenyar",
  "Slengseng",
  "Cakalang (SKJ)",
  "Lemadang",
  "Ikan Layaran (SFA)",
  "Ikan pedang (SWO)",
  "Ikan Tumbuk (SSP)",
  "Setuhuk biru (BUM)",
  "Setuhuk hitam (BLM)",
  "Setuhuk loreng (MLS)",
  "Tenggiri (COM)",
  "Tenggiri papan (GUT)",
  "Nyunglas (WAH)",
  "Ikan Gindara",
  "Ikan gergaji",
  "Cucut botol (PSK)",
  "Cucut Koboi (OCS)",
  "Cucut lanyam (FAL)",
  "Cucut Macan (TIG)",
  "Cucut martil/Capingan (SPN)",
  "Cucut Selendang (BSH)",
  "Cucut tikus/Cucut monyet (THR)",
  "Mako (MAK)",
  "Ikan Paus (RHN)",
  "Manyung",
  "Ikan sebelah",
  "Lolosi biru",
  "Kuwe",
  "Bawal hitam",
  "Bawal putih",
  "Golok golok",
  "Bawal belang",
  "Beloso/Buntut kerbo",
  "Ikan lidah",
  "Gerot-gerot",
  "Ikan gaji",
  "Ikan nomei/Lomei",
  "Kapas-kapas",
  "Peperek",
  "Lencam",
  "Kakap putih",
  "Kakap batu",
  "Kakap Sawo",
  "Kakap merah/Bambangan",
  "Jenaha",
  "Trisi",
  "Pinjalo",
  "Kurisi",
  "Kuniran",
  "Biji nangka",
  "Biji nangka karang",
  "Kurau",
  "Kuro/Senangin",
  "Swanggi/Mata besar",
  "Serinding tembakau",
  "Gulamah/Tigawaja",
  "Rejung",
  "Alu-alu/Manggilala/Pucul",
  "Senuk",
  "Kerong-kerong",
  "Layur",
  "Pari kembang/Pari macan (PSL)",
  "Pari kelelawar (MAN)",
  "Pari burung",
  "Pari hidung sekop",
  "Pari kekeh",
  "Remang/Cunang/Pucuk nipah",
  "Gabus",
  "Samgeh",
  "Kambing-kambing/Ayam-ayam",
  "Sembilang",
  "Opah",
  "Ekor kuning/Pisang-pisang",
  "Ikan napoleon",
  "Kerapu karang",
  "Kerapu bebek",
  "Kerapu balong",
  "Kerapu lumpur",
  "Kerapu sunu",
  "Beronang lingkis",
  "Beronang kuning",
  "Ikan Beronang",
  "Kakak Tua",
  "Udang dogol",
  "Udang putih/Jerbung",
  "Udang krosok",
  "Udang ratu/raja",
  "Udang windu",
  "Udang barong/Udang karang",
  "Udang kipas",
  "Udang ketak",
  "Lobster mutiara",
  "Lobster pakistan",
  "Lobster pasir",
  "Lobster bambu",
  "Lobster batik",
  "Lobster batu",
  "Kepiting",
  "Rajungan",
  "Kerang darah",
  "Kerang hijau",
  "Kerang mutiara/Tapis-tapis"
];


export const PELABUHAN_TO_KABKOTA = {
  'Pelabuhan Perikanan Banyusangka': 'Bangkalan',
  'Pelabuhan Perikanan Bawean': 'Gresik',
  'Pelabuhan Perikanan Branta Pesisir': 'Pamekasan',
  'Pelabuhan Perikanan Bulu': 'Tuban',
  'Pelabuhan Perikanan Camplong': 'Sampang',
  'Pelabuhan Perikanan Campurejo': 'Gresik',
  'Pelabuhan Perikanan Grajagan': 'Banyuwangi',
  'Pelabuhan Perikanan Lekok': 'Pasuruan',
  'Pelabuhan Perikanan Mayangan': 'Kota Probolinggo',
  'Pelabuhan Perikanan Muncar': 'Banyuwangi',
  'Pelabuhan Perikanan Ngemplakrejo': 'Kota Pasuruan',
  'Pelabuhan Perikanan Paiton': 'Probolinggo',
  'Pelabuhan Perikanan Pancer': 'Banyuwangi',
  'Pelabuhan Perikanan Pasongsongan': 'Sumenep',
  'Pelabuhan Perikanan Pondokdadap': 'Malang',
  'Pelabuhan Perikanan Popoh': 'Tulungagung',
  'Pelabuhan Perikanan Puger': 'Jember',
  'Pelabuhan Perikanan Sine': 'Tulungagung',
  'Pelabuhan Perikanan Tambakrejo': 'Blitar',
  'Pelabuhan Perikanan Tamperan': 'Pacitan'
};

export const PERBEKALAN_OPTIONS = [
  { nama: 'Es', satuan: 'Kilogram' },
  { nama: 'Air', satuan: 'Liter' },
  { nama: 'Solar', satuan: 'Liter' },
  { nama: 'Oli', satuan: 'Liter' },
  { nama: 'Bensin', satuan: 'Liter' },
  { nama: 'Umpan', satuan: 'Kilogram' },
  { nama: 'Garam', satuan: 'Kilogram' },
  { nama: 'Beras', satuan: 'Kilogram' },
  { nama: 'Gula', satuan: 'Kilogram' },
  { nama: 'Minyak Goreng', satuan: 'Liter' },
  { nama: 'Rokok', satuan: 'Press' },
  { nama: 'Freon', satuan: 'Tabung' },
  { nama: 'Gas LPG 3 Kg', satuan: 'Tabung' },
  { nama: 'Gas LPG 12 Kg', satuan: 'Tabung' }
];

