export const PELABUHAN_OPTIONS = [
  "Pelabuhan Perikanan Banyusangka",
  "Pelabuhan Perikanan Bawean",
  "Pelabuhan Perikanan Branta Pesisir",
  "Pelabuhan Perikanan Bulu",
  "Pelabuhan Perikanan Camplong",
  "Pelabuhan Perikanan Campurejo",
  "Pelabuhan Perikanan Grajagan",
  "Pelabuhan Perikanan Lekok",
  "Pelabuhan Perikanan Mayangan",
  "Pelabuhan Perikanan Muncar",
  "Pelabuhan Perikanan Ngemplakrejo",
  "Pelabuhan Perikanan Paiton",
  "Pelabuhan Perikanan Pancer",
  "Pelabuhan Perikanan Pasongsongan",
  "Pelabuhan Perikanan Pondokdadap",
  "Pelabuhan Perikanan Popoh",
  "Pelabuhan Perikanan Puger",
  "Pelabuhan Perikanan Sine",
  "Pelabuhan Perikanan Tambakrejo",
  "Pelabuhan Perikanan Tamperan"
];

export const GT_KAPAL_OPTIONS = [
  "GT 101 - 200",
  "GT 11 - 20",
  "GT 201 - 300",
  "GT 21 - 30",
  "GT 301 - 500",
  "GT 31 - 50",
  "GT 501 - 1000",
  "GT 51 - 100",
  "GT 6 - 10",
  "GT < 5",
  "GT > 1000",
  "GT > 30",
  "Jukung",
  "Kapal Motor",
  "Motor Tempel",
  "Perahu Papan Besar",
  "Perahu Papan Kecil",
  "Perahu Papan Sedang",
  "Perahu Tanpa Motor"
];

export const ALAT_TANGKAP_OPTIONS = [
  "API lainnya",
  "Alat yang Dijatuhkan atau Ditebarkan",
  "Ambai",
  "Anco",
  "Bagan Berperahu Teri atau Bagan Apung Teri",
  "Bagan Berperahu atau Bagan Apung",
  "Bagan Tancap",
  "Bale-bale",
  "Bouke Ami",
  "Bubu",
  "Bubu Bersayap",
  "Bubu Bersayap Glass Eel",
  "Bubu Gurita",
  "Bubu Naga",
  "Huhate",
  "Huhate Mekanis",
  "Jala Jatuh Berkapal",
  "Jala Tebar",
  "Jaring Angkat",
  "Jaring Hela",
  "Jaring Hela Dasar",
  "Jaring Hela Ikan Berkantong",
  "Jaring Hela Udang Berkantong",
  "Jaring Insang",
  "Jaring Insang Berlapis",
  "Jaring Insang Berpancang",
  "Jaring Insang Hanyut",
  "Jaring Insang Horizontal",
  "Jaring Insang Kombinasi",
  "Jaring Insang Lingkar",
  "Jaring Insang Tetap",
  "Jaring Lingkar",
  "Jaring Lingkar Tanpa Tali Kerut",
  "Jaring Tarik",
  "Jaring Tarik Berkantong",
  "Jaring Tarik Pantai",
  "Jaring Tarik Sempadan",
  "Jermal",
  "Ladung",
  "Panah",
  "Pancing",
  "Pancing Berjoran",
  "Pancing Cumi",
  "Pancing Cumi Mekanis",
  "Pancing Layang-Layang",
  "Pancing Ulur",
  "Pancing Ulur Tuna",
  "Payang",
  "Payang Teri",
  "Pengerih",
  "Penggaruk",
  "Penggaruk Berkapal",
  "Penggaruk Tanpa Kapal",
  "Perangkap",
  "Perangkap Benih Bening Lobster dan Benih Lobster",
  "Perre-Perre",
  "Pukat Cincin Pelagis Besar dalam Kesatuan Armada",
  "Pukat Cincin Pelagis Besar dengan Satu Kapal",
  "Pukat Cincin Pelagis Kecil dalam Kesatuan Armada",
  "Pukat Cincin Pelagis Kecil dengan Dua Kapal",
  "Pukat Cincin Pelagis Kecil dengan Satu Kapal",
  "Pukat Cincin Teri dengan Satu Kapal",
  "Pukat Dorong",
  "Pukat Labuh",
  "Pukat Labuh Teri",
  "Rawai Dasar",
  "Rawai Tuna",
  "Sero",
  "Seser",
  "Set net",
  "Togo",
  "Tombak",
  "Tonda"
];

export const KOMODITAS_OPTIONS = [
  "Albakora (Thunnus alalunga)",
  "Alu- alu (Sphyraena qenie)",
  "Alu-alu (Sphyraena barracuda)",
  "Alu-alu (Sphyraena obtusata)",
  "Anggoli (Etelis coruscans)",
  "Aruan tasek (Rachycentron canadum )",
  "Baji-baji sebra (Seriolina nigrofasciata )",
  "Bambangan (Lutjanus malabaricus)",
  "Barakuda (Sphyraena jello)",
  "Baronang (Siganus javus)",
  "Baronang lingkis  (Siganus canaliculatus)",
  "Bawal (Colossoma macropomum)",
  "Bawal hitam (Parastromateus niger)",
  "Bawal putih  (Pampus argenteus)",
  "Bawal sabit (Taractichthys steindachneri)",
  "Belanak (Mugil cephalus)",
  "Beloso (Saurida tumbil)",
  "Biji nangka (Upeneus moluccensis)",
  "Biji nangka (Upeneus spp)",
  "Bulan - Bulan (Megalops cyprinoides)",
  "Buntal karang (Diodon hystrix)",
  "Butana (Acanthurus mata)",
  "Cakalang (Katsuwonus pelamis)",
  "Cendro (Belonidae)",
  "Cendro (Tylosurus crocodilus)",
  "Cipa-cipa (Argyrops spinifer)",
  "Cobia (Rachycentron canadum )",
  "Coklatan (Scolopsis affinis)",
  "Cucut baster (Isurus paucus)",
  "Cucut lanjam (Carcharhinus cautus)",
  "Cucut lanjam (Carcharhinus melanopterus)",
  "Cucut mako (Isurus spp)",
  "Cucut martil (Eusphyra blochii)",
  "Cumi karet (Sthenoteuthis oualaniensis)",
  "Cumi-cumi (Loligo chinensis)",
  "Cumi-cumi (Loligo duvauceli)",
  "Cumi-cumi (Loligo edulis)",
  "Cumi-cumi (Loligo spp)",
  "Cumi-cumi (Loligo vulgaris)",
  "Gemprang (Ilisha elongata)",
  "Gerot-gerot (Pomadasys argenteus)",
  "Gerot-gerot (Pomadasys argyreus)",
  "Gindara (Ruvettus pretiosus)",
  "Golok-golok (Chirocentrus dorab)",
  "Gorara (Lutjanus russelli)",
  "Gorara gigi (Lutjanus erythropterus)",
  "Gulamah (Gymnocranius griseus)",
  "Gulamah (Johnius coitor)",
  "Gulamah (Otolithes ruber)",
  "Gulamah (Panna microdon)",
  "Gulamah (Pennahia argentata)",
  "Gulamah keken (Johnius amblycephalus)",
  "Gulamah papan (Chrysochir aureus)",
  "Gulamah putih (Johnius borneensis)",
  "Gurita (Octopus spp)",
  "Hiu air (Scoliodon laticaudus)",
  "Hiu bongol (Chiloscyllium punctatum)",
  "Hiu lanjam (Carcharhinus amblyrhynchoides )",
  "Hiu lonjor (Carcharhinus spp)",
  "Hiu putik (Mustelus manazo)",
  "Hiu tokek (Atelomycterus marmoratus)",
  "Ikan Setan (Lepidocybium flavobrunneum)",
  "Ikan ayam-ayam (Abalistes stellaris)",
  "Ikan jaket (Aluterus monoceros)",
  "Ikan kakatua (Scarus spp)",
  "Ikan lainnya",
  "Ikan layaran (Istiophorus platypterus)",
  "Ikan lemah (Lactarius lactarius)",
  "Ikan merah (Lutjanus erythropterus)",
  "Ikan pedang (Xiphias gladius)",
  "Ikan sebelah (Psettodes erumei)",
  "Ikan sebelah mata kanan (Poecilopsetta colorata)",
  "Jambian (Lutjanus lutjanus)",
  "Japuh (Dussumieria acuta)",
  "Kaci-kaci (Diagramma labiosum)",
  "Kaci-kaci (Plectorhinchus flavomaculatus",
  "Kaci-kaci (Plectorhinchus spp)",
  "Kakap (Choerodon anchorago)",
  "Kakap Merah (Lutjanus bitaeniatus)",
  "Kakap jenaha (Lutjanus johnii)",
  "Kakap merah (Lutjanus spp)",
  "Kakap merah (Lutjanus timorensis)",
  "Kapas-Kapas (Gerres filamentosus)",
  "Kapas-kapas (Lutjanus monostigma)",
  "Kea-kea (Siganus virgatus)",
  "Kembung lelaki (Rastrelliger kanagurta)",
  "Kembung perempuan (Rastrelliger brachysoma)",
  "Kenyar (Sarda orientalis)",
  "Kerapu (Cephalopholis aurantia)",
  "Kerapu (Epinephelus cyanopodus)",
  "Kerapu (Epinephelus radiatus)",
  "Kerapu bintik kuning (Epinephelus timorensis)",
  "Kerapu karang (Cephalopholis boenak)",
  "Kerapu lumpur (Epinephelus amblycephalus)",
  "Kerapu lumpur (Epinephelus bleekeri)",
  "Kerapu sunu (Plectropomus leopardus)",
  "Kerapu tutul (Epinephelus coioides)",
  "Kerisi (Etelis radiosus)",
  "Kerisi (Nemipterus spp)",
  "Kerisi (Pentapodus emeryii)",
  "Kerong-kerong (Lethrinus spp)",
  "Kerong-kerong (Terapon theraps)",
  "Kerong-kerong padi (Terapon puta)",
  "Ketambak (Lethrinus laticaudis)",
  "Ketang-ketang (Drepane punctata)",
  "Kuniran (Upeneus sulphureus)",
  "Kurisi (Nemipterus aurora)",
  "Kurisi (Nemipterus nematophorus)",
  "Kurisi (Nemipterus virgatus )",
  "Kurisi (Nemipterus virgatus)",
  "Kurisi bali (Pristipomoides filamentosus)",
  "Kurisi perak (Aphareus Rutilans)",
  "Kuro (Eleutheronema tetradactylum)",
  "Kuro (Polydactylus microstomus)",
  "Kuwe (Carangoides hedlandensis)",
  "Kuwe (Carangoides malabaricus)",
  "Kuwe (Carangoides oblongus)",
  "Kuwe (Caranx sexfasciatus)",
  "Kuwe (Caranx spp)",
  "Kuwe abu-abu sirip gelap (Carangoides caeruleopinnatus )",
  "Kuwe abu-abu sirip gelap (Seriola rivoliana)",
  "Kuwe moncong tumpul bulat (Carangoides ferdau)",
  "Layang (Decapterus maruadsi)",
  "Layang anggur (Decapterus kurroides)",
  "Layang benggol (Decapterus russelli)",
  "Layang deles (Decapterus macrosoma)",
  "Layang pectoralf pendek (Decapterus macarellus)",
  "Layang spp (Decapterus spp)",
  "Layur (Lepturacanthus savala)",
  "Layur (Trichiurus lepturus)",
  "Lemadang (Coryphaena hippurus)",
  "Lemuru (Sardinella lemuru)",
  "Lencam (Lethrinus lentjan)",
  "Lencam (Lethrinus spp)",
  "Lolosi biru (Caesio caerulaurea)",
  "Madidihang (Thunnus albacares)",
  "Mala (Gymnocranius elongatus)",
  "Mala (Lutjanus vitta)",
  "Manyung (Arius spp)",
  "Manyung (Netuma thalassina)",
  "Marlin biru (Makaira nigricans)",
  "Mujair (Oreochromis mossambicus )",
  "Nyunglas (Acanthocybium solandri )",
  "Parang (Macrochirichthys macrochirus )",
  "Pari burung (Aetomylaeus niehofii)",
  "Pari kekeh (Rhinobatos spp)",
  "Pari kekeh (Rhynchobatus australiae)",
  "Pari kelapa (Pastinachus ater)",
  "Pari kembang (Dasyatis kuhlii)",
  "Pari merica (Taeniura lymma)",
  "Pari mutiara (Himantura jenkinsii)",
  "Pasir-pasir (Scolopsis bilineata)",
  "Pasir-pasir (Scolopsis taenioptera)",
  "Peperek (Leiognathus berbis)",
  "Peperek (Leiognathus leuciscus)",
  "Peperek bondolan (Gazza minuta)",
  "Peperek bondolan (Leiognathus bindus)",
  "Peperek lainnya (Leiognathus spp)",
  "Peperek topang (Leiognathus equulus)",
  "Pilok (Mene maculata)",
  "Pinjala (Pristipomoides multidens )",
  "Pinjalo (Pristipomoides typus)",
  "Pisang-pisang (Caesio cuning)",
  "Rajungan (Portunus pelagicus)",
  "Rajungan (Portunus spp)",
  "Rajungan angin (Podophthalmus vigil)",
  "Rejum (Sillago sihama)",
  "Remang (Gymnothorax spp)",
  "Remang putih (Gymnothorax undulatus)",
  "Selanget (Anodontostoma chacunda)",
  "Selar (Alepes melanoptera)",
  "Selar (Selar boops)",
  "Selar bentong (Selar crumenophthalmus)",
  "Selar hijau (Atule mate)",
  "Selar komo (Alepes djedaba)",
  "Selar kuning (Selaroides leptolepis)",
  "Semar (Lampris guttatus)",
  "Sembilang (Plotosus canius)",
  "Setuhuk hitam (Istiompax indica ; Makaira Indica)",
  "Silper (Platax boersii)",
  "Siro (Amblygaster sirm)",
  "Sokang (Trachinotus blochii)",
  "Sotong (Sepia aculeata)",
  "Sotong (Sepia officinalis)",
  "Sotong (Sepia pharaonis)",
  "Sotong (Sepia recurvirostra)",
  "Sotong (Sepia spp)",
  "Sunglir (Elagatis bipinnulata)",
  "Swanggi (Priacanthus hamrur)",
  "Swanggi (Priacanthus tayenus)",
  "Talang- talang (Scomberoides tol)",
  "Talang-talang (Scomberoides commersonnianus )",
  "Talang-talang (Scomberoides tala)",
  "Tanda-tanda batu (Lutjanus decussatus)",
  "Tembang (Sardinella albella)",
  "Tembang (Sardinella fimbriata)",
  "Tembang (Sardinella gibbosa)",
  "Tembang Sardinella brachysoma)",
  "Tenggiri (Scomberomorus commerson\t)",
  "Tenggiri papan (Scomberomorus guttatus)",
  "Teri (Encrasicholina devisi)",
  "Teri (Encrasicholina spp)",
  "Teri (Stolephorus commersonii)",
  "Terman (Ulua mentalis)",
  "Tetengkek (Megalaspis cordyla)",
  "Tigawaja (Johnius dussumieri)",
  "Tongkol abu-abu (Thunnus tonggol)",
  "Tongkol banyar (Euthynnus affinis)",
  "Tongkol banyar (Euthynnus lineatus)",
  "Tongkol pisang-balaki (Auxis thazard)",
  "Tongkol pisang-cerutu (Auxis rochei)",
  "Tuna mata besar (Thunnus obesus)",
  "Udang jerbung (Penaeus merguiensis )",
  "Udang kipas (Thenus orientalis)",
  "Udang krosok (Metapenaeus spp)",
  "Udang krosok merah (Metapenaeopsis rosea)",
  "Udang pasir (Thenus orientalis)",
  "Udang putih vanamei (Penaeus vannamei)"
];
